services:
  # --- SERVICIO 1: NGINX (El único que da la cara) ---
  nginx:
    image: nginx:alpine
    container_name: budgetbuddy-nginx
    restart: unless-stopped
    ports:
      - "80:80" # ÚNICO PUERTO ABIERTO AL MUNDO
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./backend:/var/www/html # <--- Asegúrate de que Nginx pueda ver el backend (PROVISIONAL)
    depends_on:
      - frontend
    networks:
      - budgetbuddy_net

  # --- SERVICIO 2: BACKEND (Oculto en la red interna) ---
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: budgetbuddy-backend
    restart: unless-stopped
    # SIN PORTS (Requisito del enunciado)
    volumes:
      - ./backend:/var/www/html

    networks:
      - budgetbuddy_net

  # --- SERVICIO 3: FRONTEND (Oculto en la red interna) ---
  frontend:
    build:
      context: ./frontend # <--- La carpeta real
      dockerfile: Dockerfile # <--- Tu archivo con Node
    container_name: frontend
    volumes:
      - ./frontend:/app # <--- Sincroniza tu código
      - /app/node_modules # <--- Protege las librerías de Linux
    ports: # <--- IMPORTANTE: Si usas Vite/Node
      - "5173:5173" # <--- Puerto de desarrollo (no el 80)
    networks:
      - budgetbuddy_net

  #   # --- SERVICIO 4: BASE DE DATOS ---
  db:
    image: mysql:8.0
    container_name: budgetbuddy-db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: budgetbuddy
    networks:
      - budgetbuddy_net

  # --- SERVICIO 5: PHPMYADMIN (Gestor Visual) ---
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: budgetbuddy-pma
    restart: always
    ports:
      - "8080:80" # Accederemos por el puerto 8080 para no chocar con Nginx
    environment:
      PMA_HOST: db # <--- ¡CLAVE! Dice: "Conéctate al contenedor llamado 'db'"
      MYSQL_ROOT_PASSWORD: root # La misma pass que pusiste en el servicio db
    depends_on:
      - db
    networks:
      - budgetbuddy_net
networks:
  budgetbuddy_net:
    driver: bridge
